Add matching queue
CS3219-AY2425S1/cs3219-ay2425s1-project-g52 pull request #13
Opened 2024-10-12 11:12 UTC by anuanas2007

This pull request introduces the implementation of the matching queue functionality in the backend service. It includes the setup of necessary connections, initialization of services, and handling of match requests.

2024-10-12 15:23 UTC, freddychenyouren2 commented on backend/matching-service/src/index.js
> +          matchQueue[i].userId !== matchRequest.userId
There are three conditions within this if-block. You may want to consider creating a boolean function that checks the matching criteria for better readability.

As an extension, you may want to consider having two types of such boolean functions:
1. `meetHardMatchingCriteria()`: Both `topic` and `difficulty` of the two users must equal before they are matched.
2. `meetSoftMatchingCriteria()`: Only `topic` of the two users are equal.

2024-10-12 15:24 UTC, freddychenyouren2 commented on backend/matching-service/src/index.js
> +            matchQueue[i].userId !== matchRequest.userId
Similar comment to above at line 40.

2024-10-12 15:28 UTC, freddychenyouren2 commented on backend/matching-service/src/matchQueue.js
> +    }, 60000);
For the Timeout duration, 60 seconds may be too long. The Project Documentation and our plan in D1 are both 30 seconds. You may change the setTimeout duration from `60000` to `30000`.

2024-10-12 15:32 UTC, freddychenyouren2 requested changes
Some small changes and suggestions on code readability and time limit of matching service.

2024-10-13 15:32 UTC, btaanish commented
Need the matching service backend to test out compatibity in the frontend side of things, will make the expected changes in my PR

2024-10-13 15:32 UTC, merged